[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://main--stellular-kitten-88e0a5.netlify.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws/*"
  to = "wss://main--stellular-kitten-88e0a5.netlify.app/api/ws/:splat"
  status = 101
  force = true


[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS, PUT, DELETE"
    Content-Security-Policy = "connect-src wss://main--stellular-kitten-88e0a5.netlify.app/api/ws"

[[redirects]]
  from = "/"
  to = "/index"
  status = 302
